---
- name: Deploy web server on VM1 and VM2
  hosts: webservers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Assign VM number
      set_fact:
        vm_num: "{{ '1' if 'VM1' in inventory_hostname else '2' }}"

    - name: Create index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hello World</title>
          </head>
          <body>
              Hello World from SJSU-{{ vm_num }}
          </body>
          </html>

    - name: Configure nginx to listen on port 8080
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: 'listen\s+80\s+default_server;'
        line: 'listen 8080 default_server;'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
