- name: Un-deploy web server
  hosts: webservers
  become: yes
  tasks:
    - name: Stop nginx service
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: Remove nginx package
      ansible.builtin.apt:
        name: nginx
        state: absent

    - name: Remove index.html file
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
